version: alpha

accounts:
  - name: staker-1
    id: 2
  - name: staker-2
    id: 3
  - name: staker-3
    id: 4

pipelines:
  delegate-test:
  - task: transfer
    destination: $staker-1
    amount: 6_100_000_000
  - task: transfer
    destination: $staker-2
    amount: 6_100_000_000
  - task: transfer
    destination: $staker-3
    amount: 6_100_000_000
  - task: set_baker_params
    source: $mbb
    edge: 1_000_000_000
    limit: 5_000_000
  - task: wait
    for: cycle
    value: +5
  # setup staker delegation and stake
  - task: delegate
    source: $staker-1
    destination: $mbb
  - task: delegate
    source: $staker-2
    destination: $mbb
  - task: delegate
    source: $staker-3
    destination: $mbb
  - task: stake
    source: $staker-1
    amount: 5_000_000_000
  - task: stake
    source: $staker-2
    amount: 5_000_000_000
  - task: stake
    source: $staker-3
    amount: 5_000_000_000
  - task: wait
    for: cycle
    value: +1
  - task: unstake
    source: $staker-1
    amount: 5_000_000_000
  - task: wait
    for: cycle
    value: +5