---
name: Feature request
about: Create a note for things that can be added to TzGo
assignees: ""
---

## Description

<!-- Describe what you would like to see in TzGo, including the desired interface, typing, etc. -->

### Relevant protocol version

<!-- If the feature is related to a specific protocol version, please add the information here -->

## Notes

<!-- Miscellaneous things that might help with prioritisation, e.g. how urgently you need this -->
